erDiagram
TABLE   {
type                      object
year                       int64
country                   object
host                      object
start             datetime64[ns]
end               datetime64[ns]
duration                   int64
countries                  int64
events                     int64
sports                     int64
participants_m             int64
participants_f             int64
participants               int64
Code                      object
}